CREATE TABLE forum_post_votes (id SERIAL NOT NULL, post_id INT DEFAULT NULL, user_id INT DEFAULT NULL, points SMALLINT DEFAULT '1' NOT NULL, reason VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_44A64B654B89032C ON forum_post_votes (post_id);
CREATE INDEX IDX_44A64B65A76ED395 ON forum_post_votes (user_id);
ALTER TABLE forum_post_votes ADD CONSTRAINT FK_44A64B654B89032C FOREIGN KEY (post_id) REFERENCES forum_posts (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forum_post_votes ADD CONSTRAINT FK_44A64B65A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE forum_posts ADD votes INT DEFAULT 0 NOT NULL;
CREATE UNIQUE INDEX UNIQ_44A64B65A76ED3954B89032C ON forum_post_votes (user_id, post_id);
